services:

 postgres:
  container_name: postgres
  image: postgres:latest
  ports:
    - 5432:5432
  restart: always
  user: postgres
  env_file: .env
  volumes:
      - ./database/data:/data/postgres
  networks:
    - db

 backend:
  container_name: backend
  depends_on:
   - postgres
  build:
    dockerfile: Dockerfile
    context: ./backend
  env_file: ./backend/back.env
  command: npm run start:dev
  restart: unless-stopped
  ports:
   - 3003:3003
  networks:
   - db

 frontend:
  container_name: frontend
  depends_on:
   - backend
  env_file: ./frontend/front.env
  command: npm run dev
  build: 
   dockerfile: Dockerfile
   context: ./frontend
  ports:
   - 8080:8080

networks:
 db:

